import { c as create_ssr_component, p as add_attribute } from "../../../chunks/ssr.js";
import "../../../chunks/client.js";
const css = {
  code: "form.svelte-1gejasz.svelte-1gejasz{max-width:960px;margin:0 auto;display:flex;flex-direction:column;gap:20px}h1.svelte-1gejasz.svelte-1gejasz{color:#fff}form.svelte-1gejasz label.svelte-1gejasz{color:#fff}form.svelte-1gejasz input.svelte-1gejasz{line-height:1.5em}.two-col.svelte-1gejasz.svelte-1gejasz{display:grid;grid-template-columns:1fr 1fr;gap:20px}.two-col.svelte-1gejasz div.svelte-1gejasz,.one-col.svelte-1gejasz.svelte-1gejasz{display:flex;flex-direction:column;gap:10px}button.svelte-1gejasz.svelte-1gejasz{padding:15px 0;cursor:pointer}",
  map: '{"version":3,"file":"+page.svelte","sources":["+page.svelte"],"sourcesContent":["<script>\\n    import {enhance} from \\"$app/forms\\";\\n  import ContractForm from \\"$lib/components/ContractForm.svelte\\";\\n\\n  let date = new Date();\\n    \\n    let minDatePicker = new Date().toISOString().split(\\"T\\")[0];\\n\\n<\/script>\\n<form action=\\"?/booking\\" method=\\"POST\\" use:enhance>\\n  <h1>Book an Event</h1>\\n  <div class=\\"two-col\\">\\n    <div>\\n      <label for=\\"first_name\\">First Name</label>\\n      <input type=\\"text\\" name=\\"first_name\\" value=\\"John\\" required/>\\n    </div>\\n    <div>\\n      <label for=\\"last_name\\">Last Name</label>\\n      <input type=\\"text\\" name=\\"last_name\\" value=\\"Smith\\" required/>\\n    </div>\\n  </div>\\n  <div class=\\"two-col\\">\\n    <div>\\n      <label for=\\"email\\">Email</label>\\n      <input type=\\"email\\" name=\\"email\\" value=\\"test@magiknsap.ca\\" required/>\\n    </div>\\n    <div>\\n      <label for=\\"phone\\">Phone</label>\\n      <input type=\\"number\\" id=\\"phone\\" name=\\"phone\\" value=\\"4168813415\\" minlength=\\"10\\" maxlength=\\"10\\" inputmode=\\"numeric\\" required />\\n    </div>\\n  </div>\\n  <div class=\\"two-col\\">\\n    <div>\\n      <label for=\\"event_location\\">Location</label>\\n      <input type=\\"text\\" name=\\"event_location\\" value=\\"scarborough\\" required/>\\n    </div>\\n    <div>\\n      <label for=\\"event_date\\">Event Date</label>\\n      <input type=\\"date\\"  min={minDatePicker} value={minDatePicker} name=\\"event_date\\" required>\\n    </div>\\n  </div>\\n  <div class=\\"one-col\\">\\n    <label for=\\"comment\\">Additional Info</label>\\n    <textarea name=\\"comment\\" cols=\\"13\\" rows=\\"10\\" required></textarea>\\n  </div>\\n  <button type=\\"submit\\">Submit</button>\\n</form>\\n<style lang=\\"scss\\">form {\\n  max-width: 960px;\\n  margin: 0 auto;\\n  display: flex;\\n  flex-direction: column;\\n  gap: 20px;\\n}\\n\\nh1 {\\n  color: #fff;\\n}\\n\\nform label {\\n  color: #fff;\\n}\\n\\nform input {\\n  line-height: 1.5em;\\n}\\n\\n.two-col {\\n  display: grid;\\n  grid-template-columns: 1fr 1fr;\\n  gap: 20px;\\n}\\n\\n.two-col div, .one-col {\\n  display: flex;\\n  flex-direction: column;\\n  gap: 10px;\\n}\\n\\nbutton {\\n  padding: 15px 0;\\n  cursor: pointer;\\n}</style>"],"names":[],"mappings":"AA+CmB,kCAAK,CACtB,SAAS,CAAE,KAAK,CAChB,MAAM,CAAE,CAAC,CAAC,IAAI,CACd,OAAO,CAAE,IAAI,CACb,cAAc,CAAE,MAAM,CACtB,GAAG,CAAE,IACP,CAEA,gCAAG,CACD,KAAK,CAAE,IACT,CAEA,mBAAI,CAAC,oBAAM,CACT,KAAK,CAAE,IACT,CAEA,mBAAI,CAAC,oBAAM,CACT,WAAW,CAAE,KACf,CAEA,sCAAS,CACP,OAAO,CAAE,IAAI,CACb,qBAAqB,CAAE,GAAG,CAAC,GAAG,CAC9B,GAAG,CAAE,IACP,CAEA,uBAAQ,CAAC,kBAAG,CAAE,sCAAS,CACrB,OAAO,CAAE,IAAI,CACb,cAAc,CAAE,MAAM,CACtB,GAAG,CAAE,IACP,CAEA,oCAAO,CACL,OAAO,CAAE,IAAI,CAAC,CAAC,CACf,MAAM,CAAE,OACV"}'
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  let minDatePicker = (/* @__PURE__ */ new Date()).toISOString().split("T")[0];
  $$result.css.add(css);
  return `<form action="?/booking" method="POST" class="svelte-1gejasz"><h1 class="svelte-1gejasz" data-svelte-h="svelte-itpf52">Book an Event</h1> <div class="two-col svelte-1gejasz" data-svelte-h="svelte-gftx8a"><div class="svelte-1gejasz"><label for="first_name" class="svelte-1gejasz">First Name</label> <input type="text" name="first_name" value="John" required class="svelte-1gejasz"></div> <div class="svelte-1gejasz"><label for="last_name" class="svelte-1gejasz">Last Name</label> <input type="text" name="last_name" value="Smith" required class="svelte-1gejasz"></div></div> <div class="two-col svelte-1gejasz" data-svelte-h="svelte-1sgwyb0"><div class="svelte-1gejasz"><label for="email" class="svelte-1gejasz">Email</label> <input type="email" name="email" value="test@magiknsap.ca" required class="svelte-1gejasz"></div> <div class="svelte-1gejasz"><label for="phone" class="svelte-1gejasz">Phone</label> <input type="number" id="phone" name="phone" value="4168813415" minlength="10" maxlength="10" inputmode="numeric" required class="svelte-1gejasz"></div></div> <div class="two-col svelte-1gejasz"><div class="svelte-1gejasz" data-svelte-h="svelte-1gci7v9"><label for="event_location" class="svelte-1gejasz">Location</label> <input type="text" name="event_location" value="scarborough" required class="svelte-1gejasz"></div> <div class="svelte-1gejasz"><label for="event_date" class="svelte-1gejasz" data-svelte-h="svelte-k2wa3">Event Date</label> <input type="date"${add_attribute("min", minDatePicker, 0)}${add_attribute("value", minDatePicker, 0)} name="event_date" required class="svelte-1gejasz"></div></div> <div class="one-col svelte-1gejasz" data-svelte-h="svelte-14avyif"><label for="comment" class="svelte-1gejasz">Additional Info</label> <textarea name="comment" cols="13" rows="10" required></textarea></div> <button type="submit" class="svelte-1gejasz" data-svelte-h="svelte-1ou7dtz">Submit</button> </form>`;
});
export {
  Page as default
};
